### ISSUE TITLE
propsをローカル変数展開して簡潔に書く

### ISSUE THREAD

**Issue by hiraike32** [chao7150/react-todo#13]
ReactのTipsですが...

```
const App = (props: Props) => {
  const listItems = props.contents.map(() =>)
  ...
}
```

は、ローカル変数に展開しておく事で、以下のようにも書けます。

```
const App = ({contents}: Props) => {
  const listItems = contents.map(() =>)
  ...
}
```

こうしておけば、呼び出すときに毎回 `props.foo` としなくても良くなります。

**Comment by chao7150** [comment]
ありがとうございます。ふーんできるんだ、いやこれマジでできるの？と驚きました。
[MDN](https://developer.mozilla.org/ja/docs/Web/JavaScript/Reference/Operators/Destructuring_assignment#Assignment_without_declaration)によるとvar相当っぽく書かれてますね。関数の中で再代入できました。
```
const obj = { a: 1, b: 2 }
const func = ({ a, b }) => {
  a = 3
  console.log(a, b)
}
func(obj)  // 3 2
```
多くの情報をpropsにまとめることが多いReactでは使い勝手のいいテクニックですね。
