### ISSUE TITLE
TypeScriptで書く

### ISSUE THREAD

**Issue by hiraike32** [chao7150/react-todo#6]
TypeScriptで書いたほうが、補完が聞くので開発のスピードが上がり、かつミスが少なくなるので、早い段階で導入することをおすすめします。
https://facebook.github.io/create-react-app/docs/adding-typescript

出来上がってから書き直すのはけっこう大変なので。。。

**Comment by chao7150** [comment]
やるぞ！やるぞ！

**Comment by chao7150** [comment]
やりました
